#-------------------------------
# General Site Settings

title: Benjamin
logo: 
author: Benjamin
description: this is meta description
email: bianfusia@gmail.com
#phone: +880 2544 658 256
#address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: Portfolio, link: '/bianfusia-profile/portfolio'}

#-------------------------------
# Hero Section

hero:
  hero-title: Digital Forensics Examiner <br> & Coding Enthusiast

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Mobile Forensics, color: '#fdb157', value: '90%'}
- {name: Computer Forensics, color: '#9473e6', value: '90%'}
- {name: Python Programming, color: '#bdecf6', value: '80%'}
- {name: Javascript Programming, color: '#fff700', value: '70%'}
- {name: SQL, color: '#fff700', value: '60%'}
- {name: RPA, color: '#bdecf6', value: '60%'}
- {name: Burpsuite, color: '#9473e6', value: '50%'}
- {name: Metasploit, color: '#ffbcaa', value: '40%'}

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Investigation Officer, icon: 'icon-1.png', date: 'Nov 2013 - Jul 2019', organization: 'CPFB'}
- {name: Manager (Enforcement), icon: 'icon-2.png', date: 'Jul 2019 - Aug 2021', organization: 'ACRA'}
- {name: Senior Forensics Examiner, icon: 'icon-3.png', date: 'Sep 2021 - Present', organization: 'CPIB'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Bachelor of Science in Marketing, date: '2018', organization: 'Singapore University of Social Sciences'}
- {name: Diploma in Business Management, date: '2011', organization: 'Nanyang Polytechnic'}

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-7.png"
    url: "https://hackerone.com/bianfusia?type=user"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "https://t.me/ekittens_bot"
    
  - image : "assets/images/portfolio/item-6.png"
    url: "https://www.codingame.com/profile/221413db467dadf86cd7805e40c30d9d6046083"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "https://play.google.com/store/apps/details?id=xyz.beeeatant.sis"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "https://tryhackme.com/p/bianfusia"


# Portfolio Page
portfolio-label:
- {
    title : "COMPETITION",
    type : "design"
  }
- {
    title : "HACKING",
    type : "branding"
  }
- {
    title : "APPS/BOTS",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      

